# site settings
title: Hackbridge
subtitle: .i/o
email: hello@hackbridge.io
description: Kindling tech entrepreneurship at Cambridge University
url: "" # the base hostname & protocol for your site
author: Imran Ahmed
street_address:
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/hackbridge
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
